// web/socialsci-vue/src/views/workflow/LiteratureMatrixPanel.vue
<script setup lang="ts">
/**
 * LiteratureMatrixPanel —— 文献提取矩阵(Elicit 式「选论文集 → 定列 → 逐篇提取成表」)
 *
 * 由来(2026-09-24): `POST /api/literature/matrix` 后端早就有了, **外壳也接了**
 *   (`web/src/components/LiteratureMatrixPanel.tsx`), 但写作舱零引用 ——
 *   而"把已选文献摆成一张对照表"恰恰是写文献综述那一步最需要的东西。
 *
 * 与外壳那个面板的差别(不是重复实现):
 *   · 外壳的论文清单来自「文献库」当前那一页(`LiteraturePanel` 传的是分页后的 items),
 *     也就是"我在库里翻到哪就提取哪几篇";
 *   · 这里是**写作舱已整理的文献素材** —— 也就是这个课题真正要用、已经在写的那批。
 *
 * ⚠ 成本: 这个端点是全仓单次调用最贵的 —— 后端对**每一篇**各调一次 LLM(上限 30 篇,
 *   每篇 12k 字符 prompt)。所以这里必须把还没选时的状态说清楚, 让用户知道自己在点的是什么;
 *   同时服务端已把它纳入额度闸门(BUDGET_GATED_PREFIXES, 2026-09-24 补)。
 */
import { computed, ref } from "vue";
import { toast } from "@/shared/ui";
import { q } from "@/shared/api";
import EmptyState from "./EmptyState.vue";

interface RefEntry { title?: string; doi?: string; year?: string; author?: string; authors?: string }

const props = defineProps<{
  /** 写作舱已整理的文献素材(其 references 会被摊平成待提取的论文清单) */
  materials: Array<Record<string, unknown>>;
}>();

interface Paper { id: string; title: string }

/**
 * 待提取的论文清单 —— 取文献素材的 `references`。
 *
 * 为什么用 `title` 当 id: 后端的 `literature-matrix-service` 走的是
 * `literatureService.getDetail(paperId)`(本地文献库主键), 而这些 reference 条目
 * **未必在本地库里**(可能是手工录入或检索后只存了素材)。
 * 所以这里的 id 用标题 —— 与后端 `loadPaperText` 的兜底口径一致: 命中不了就用标题找。
 * 命不中的会在返回的 `warnings` 里点名, 面板照实显示, 不假装全都提取到了。
 */
const papers = computed<Paper[]>(() => {
  const out: Paper[] = [];
  const seen = new Set<string>();
  for (const m of props.materials ?? []) {
    const refs = m.references;
    if (!Array.isArray(refs)) continue;
    for (const r of refs as RefEntry[]) {
      const t = String(r?.title ?? "").trim();
      if (!t || seen.has(t)) continue;
      seen.add(t);
      out.push({ id: t, title: t });
    }
  }
  return out;
});

/** 内置提取列 —— 与后端/外壳同一套(研究主题/方法/数据/观点/结论/局限) */
const COMMON_COLS = [
  { key: "topic", label: "研究主题" },
  { key: "method", label: "研究方法" },
  { key: "data", label: "数据来源" },
  { key: "view", label: "核心观点" },
  { key: "conclusion", label: "主要结论" },
  { key: "limitation", label: "局限" },
];
const pickedCols = ref<string[]>(COMMON_COLS.slice(0, 3).map((c) => c.key));
const customCols = ref<{ key: string; label: string }[]>([]);
const newCol = ref("");
const allCols = computed(() => [...COMMON_COLS, ...customCols.value]);

interface MatrixCell { paperId: string; paperTitle: string; columnKey: string; value: string; quote?: string }
interface MatrixResult { papers: Array<{ id: string; title: string }>; cells: MatrixCell[]; warnings?: string[] }

const running = ref(false);
const result = ref<MatrixResult | null>(null);
const openQuote = ref("");

function toggleCol(k: string) {
  const next = pickedCols.value.includes(k) ? pickedCols.value.filter((x) => x !== k) : [...pickedCols.value, k];
  pickedCols.value = next;
}
function addCol() {
  const label = newCol.value.trim();
  if (!label) return;
  const key = "custom" + Math.random().toString(36).slice(2, 8);
  customCols.value = [...customCols.value, { key, label }];
  pickedCols.value = [...pickedCols.value, key];
  newCol.value = "";
}

async function run() {
  if (!papers.value.length) { toast("还没有可提取的文献（请先在文献素材里录入参考文献条目）", "warning"); return; }
  const cols = allCols.value.filter((c) => pickedCols.value.includes(c.key));
  if (!cols.length) { toast("请至少选择一列要提取的内容", "warning"); return; }
  if (papers.value.length > 30) { toast(`最多一次提取 30 篇，当前 ${papers.value.length} 篇`, "warning"); return; }
  running.value = true;
  result.value = null;
  try {
    const r = await q<MatrixResult>(`/literature/matrix`, {
      method: "POST",
      body: { paperIds: papers.value.slice(0, 30).map((p) => p.id), columns: cols },
    });
    result.value = r;
    const cells = r?.cells?.length ?? 0;
    toast(cells ? `提取完成：${cells} 个单元格` : "提取完成，但没有取到内容", cells ? "success" : "warning");
  } catch (e) {
    toast(`提取失败：${(e as Error).message}`, "error");
  } finally {
    running.value = false;
  }
}

/** 矩阵渲染: 行=论文, 列=提取项 */
const matrix = computed(() => {
  const r = result.value;
  if (!r) return { rows: [] as Array<{ paper: { id: string; title: string }; cells: Record<string, { value: string; quote?: string }> }>, cols: [] as typeof COMMON_COLS };
  const cols = allCols.value.filter((c) => pickedCols.value.includes(c.key));
  const rows = (r.papers ?? []).map((p) => {
    const cells: Record<string, { value: string; quote?: string }> = {};
    for (const c of cols) {
      const hit = r.cells.find((x) => x.paperId === p.id && x.columnKey === c.key);
      cells[c.key] = { value: hit?.value ?? "", ...(hit?.quote ? { quote: hit.quote } : {}) };
    }
    return { paper: p, cells };
  });
  return { rows, cols };
});

function exportCsv() {
  const m = matrix.value;
  if (!m.rows.length) return;
  const esc = (s: string) => `"${String(s ?? "").replace(/"/g, '""').replace(/[\r\n]+/g, " ")}"`;
  const head = ["文献", ...m.cols.map((c) => c.label)].map(esc).join(",");
  const body = m.rows.map((r) => [r.paper.title, ...m.cols.map((c) => r.cells[c.key]?.value ?? "")].map(esc).join(","));
  // BOM: 不带头 Excel 打开中文是乱码
  const blob = new Blob(["﻿" + [head, ...body].join("\n")], { type: "text/csv;charset=utf-8" });
  const a = document.createElement("a");
  a.href = URL.createObjectURL(blob);
  a.download = "文献提取矩阵.csv";
  a.click();
  URL.revokeObjectURL(a.href);
}
</script>

<template>
  <div class="lmp">
    <p class="lmp-sub">
      把已整理的文献摆成一张对照表，一列一项内容。每篇各调一次模型提取，所以
      <strong>选几列、提取几篇</strong>都直接影响耗时与用量。
    </p>

    <EmptyState
      v-if="!papers.length"
      title="还没有可提取的文献"
      hint="先在「文献与资料」里录入文献素材（含参考文献条目），再回来做提取矩阵。"
    />

    <template v-else>
      <div class="lmp-cols">
        <span class="lmp-cols-label">提取列</span>
        <button
          v-for="c in allCols" :key="c.key"
          class="lmp-chip" :class="{ on: pickedCols.includes(c.key) }"
          :data-control="`workflow:matrix-col-${c.key}`"
          @click="toggleCol(c.key)"
        >{{ c.label }}</button>
        <input v-model="newCol" class="lmp-newcol" placeholder="自定义列…" @keyup.enter="addCol" />
        <button v-if="newCol.trim()" class="lmp-addcol" data-control="workflow:matrix-addcol" @click="addCol">+ 添加</button>
      </div>

      <div class="lmp-actions">
        <span class="lmp-count">共 {{ papers.length }} 篇文献 · 已选 {{ pickedCols.length }} 列</span>
        <button class="lmp-btn lmp-btn--go" data-control="workflow:matrix-run" :disabled="running || !pickedCols.length" @click="run">
          {{ running ? "提取中…" : "开始提取" }}
        </button>
        <button v-if="matrix.rows.length" class="lmp-btn" data-control="workflow:matrix-export" @click="exportCsv">导出 CSV</button>
      </div>

      <!-- warnings 照实显示: 后端对那些"在本地库里找不到"的论文会点名, 藏起来会让人以为全提取到了 -->
      <p v-if="result?.warnings?.length" class="lmp-warn">
        {{ result.warnings.length }} 条提示：{{ result.warnings.slice(0, 3).join("；") }}
      </p>

      <div v-if="matrix.rows.length" class="lmp-table-wrap">
        <table class="three-line-table lmp-table">
          <thead>
            <tr>
              <th class="lmp-th-paper">文献</th>
              <th v-for="c in matrix.cols" :key="c.key">{{ c.label }}</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="row in matrix.rows" :key="row.paper.id">
              <td class="lmp-td-paper" :title="row.paper.title">{{ row.paper.title }}</td>
              <td v-for="c in matrix.cols" :key="c.key">
                <span v-if="row.cells[c.key]?.value">{{ row.cells[c.key].value }}</span>
                <span v-else class="lmp-empty">—</span>
                <button
                  v-if="row.cells[c.key]?.quote"
                  class="lmp-quote-btn"
                  @click="openQuote = openQuote === row.paper.id + c.key ? '' : row.paper.id + c.key"
                >引文</button>
                <p v-if="row.cells[c.key]?.quote && openQuote === row.paper.id + c.key" class="lmp-quote">
                  {{ row.cells[c.key].quote }}
                </p>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </template>
  </div>
</template>

<style scoped>
.lmp { display: flex; flex-direction: column; gap: var(--wf-s3); }
.lmp-sub { margin: 0; font-size: var(--wf-f-sm); color: var(--wf-muted); line-height: 1.7; }
.lmp-sub strong { color: var(--wf-text-2); }
.lmp-cols { display: flex; flex-wrap: wrap; align-items: center; gap: 6px; }
.lmp-cols-label { font-size: var(--wf-f-xs); color: var(--wf-faint); margin-right: 2px; }
.lmp-chip {
  cursor: pointer; border-radius: var(--wf-r-pill); padding: 3px 11px;
  font-size: var(--wf-f-xs); background: transparent;
  border: 1px solid var(--wf-line-strong); color: var(--wf-muted);
  transition: all var(--wf-dur-fast) var(--wf-ease);
}
.lmp-chip.on { border-color: var(--wf-accent); color: var(--wf-accent-hi); background: var(--wf-accent-soft); }
.lmp-newcol {
  border: 1px solid var(--wf-line); border-radius: var(--wf-r-sm);
  background: var(--wf-surface-2); color: var(--wf-text); padding: 3px 9px; font-size: var(--wf-f-xs); width: 110px;
}
.lmp-addcol {
  cursor: pointer; border: 1px solid var(--wf-line-strong); border-radius: var(--wf-r-sm);
  background: transparent; color: var(--wf-text-2); padding: 3px 9px; font-size: var(--wf-f-xs);
}
.lmp-actions { display: flex; align-items: center; gap: var(--wf-s2); }
.lmp-count { font-size: var(--wf-f-xs); color: var(--wf-faint); }
.lmp-btn {
  cursor: pointer; border: 1px solid var(--wf-line-strong); border-radius: var(--wf-r-sm);
  background: transparent; color: var(--wf-text-2); padding: 5px 12px; font-size: var(--wf-f-sm);
  transition: background var(--wf-dur-fast) var(--wf-ease);
}
.lmp-btn:hover:not(:disabled) { background: var(--wf-raised); }
.lmp-btn:disabled { opacity: .5; cursor: not-allowed; }
.lmp-btn--go { margin-left: auto; border-color: var(--wf-accent); color: var(--wf-accent-hi); }
.lmp-btn--go:hover:not(:disabled) { background: var(--wf-accent-soft); }
.lmp-warn { margin: 0; font-size: var(--wf-f-xs); color: var(--wf-warn); line-height: 1.6; }
.lmp-table-wrap { overflow-x: auto; }
.lmp-table { font-size: var(--wf-f-xs); }
.lmp-th-paper, .lmp-td-paper { max-width: 220px; }
.lmp-td-paper { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.lmp-empty { color: var(--wf-faint); }
.lmp-quote-btn {
  margin-left: 6px; cursor: pointer; border: 0; background: transparent;
  color: var(--wf-accent-hi); font-size: 10px; text-decoration: underline; padding: 0;
}
.lmp-quote {
  margin: 4px 0 0; padding: 4px 7px; border-left: 2px solid var(--wf-line-strong);
  color: var(--wf-muted); font-size: var(--wf-f-xs); line-height: 1.6;
}
</style>

// web/src/components/LiteratureMatrixPanel.tsx
// SPDX-License-Identifier: AGPL-3.0-or-later WITH MarxSphere-Exception
// LiteratureMatrixPanel.tsx — 文献提取矩阵(参考 Elicit 数据提取成表; 融入文献库)
// 用法: 从文献列表勾选论文 → 定义提取列(内置常用列 + 自定义) → LLM 逐篇提取 → 可排序表 + 导出 CSV
import { useMemo, useState } from "react";
import { Download, Loader2, Plus, Table2, X } from "lucide-react";

interface MatrixPaper { id: string; title: string }
interface MatrixCell { paperId: string; paperTitle: string; columnKey: string; value: string; quote?: string }
interface ColDef { key: string; label: string }

const COMMON_COLS: ColDef[] = [
  { key: "topic", label: "研究主题" },
  { key: "method", label: "研究方法" },
  { key: "data", label: "数据来源" },
  { key: "view", label: "核心观点" },
  { key: "conclusion", label: "主要结论" },
  { key: "limitation", label: "局限" },
];

export function LiteratureMatrixPanel({ papers }: { papers: MatrixPaper[] }) {
  const [paperIds, setPaperIds] = useState<string[]>([]);
  const [cols, setCols] = useState<ColDef[]>(COMMON_COLS.slice(0, 3));
  const [customLabel, setCustomLabel] = useState("");
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState<{ papers: MatrixPaper[]; cells: MatrixCell[] } | null>(null);
  const [msg, setMsg] = useState("");
  const [sortCol, setSortCol] = useState<string | null>(null);
  const [quotePaper, setQuotePaper] = useState<string | null>(null);

  const togglePaper = (id: string) => {
    setPaperIds((prev) => (prev.includes(id) ? prev.filter((x) => x !== id) : [...prev, id]));
  };
  const toggleCol = (c: ColDef) => {
    setCols((prev) => (prev.some((x) => x.key === c.key) ? prev.filter((x) => x.key !== c.key) : [...prev, c]));
  };
  const addCustomCol = () => {
    if (!customLabel.trim()) return;
    const key = `custom${Date.now().toString(36)}`;
    setCols((prev) => [...prev, { key, label: customLabel.trim() }]);
    setCustomLabel("");
  };

  const run = async () => {
    if (paperIds.length === 0) { setMsg("先勾选论文(≥1)"); return; }
    if (cols.length === 0) { setMsg("至少选 1 个提取列"); return; }
    setLoading(true); setMsg("");
    try {
      const res = await fetch("/api/literature/matrix", {
        method: "POST", headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ paperIds, columns: cols }),
      });
      const d = await res.json();
      if (!res.ok) { setMsg(d?.error?.message ?? `失败: HTTP ${res.status}`); return; }
      setResult({ papers: d.papers ?? [], cells: d.cells ?? [] });
      setMsg(`✅ 提取完成: ${(d.papers ?? []).length} 篇 × ${cols.length} 列`);
    } catch (e) { setMsg(e instanceof Error ? e.message : String(e)); }
    finally { setLoading(false); }
  };

  // 单元格按 paper×col 排布
  const table = useMemo(() => {
    if (!result) return null;
    const rows = result.papers.map((p) => {
      const row: Record<string, string> = { _paperId: p.id, _title: p.title };
      for (const c of cols) {
        const cell = result.cells.find((x) => x.paperId === p.id && x.columnKey === c.key);
        row[c.key] = cell?.value ?? "";
      }
      return row;
    });
    if (sortCol) {
      rows.sort((a, b) => (a[sortCol] ?? "").localeCompare(b[sortCol] ?? "", "zh"));
    }
    return rows;
  }, [result, cols, sortCol]);

  const exportCsv = () => {
    if (!table) return;
    const head = ["论文", ...cols.map((c) => c.label)];
    const lines = table.map((r) => [r._title, ...cols.map((c) => (r[c.key] ?? "").replace(/[\n,]/g, " "))]);
    const csv = [head, ...lines].map((l) => l.map((x) => `"${x}"`).join(",")).join("\n");
    const blob = new Blob(["﻿" + csv], { type: "text/csv;charset=utf-8" });
    const a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "文献提取矩阵.csv";
    a.click();
    URL.revokeObjectURL(a.href);
  };

  return (
    <div className="rounded-lg border border-sky-400/20 bg-sky-400/[0.03] p-3">
      <div className="flex flex-wrap items-center gap-2 text-xs font-medium text-sky-200/90">
        <Table2 className="h-4 w-4" /> 文献提取矩阵
        <span className="text-[9px] font-normal text-muted-foreground/60">勾选论文 → 定义提取列 → LLM 逐篇提取成表(参考 Elicit)</span>
        <span className="ml-auto text-[10px] text-muted-foreground/60">已选 {paperIds.length} 篇</span>
      </div>

      <div className="mt-2 space-y-2">
        {/* 论文选择 */}
        <div>
          <div className="mb-1 text-[10px] text-muted-foreground/60">论文(点击勾选):</div>
          <div className="max-h-24 space-y-0.5 overflow-y-auto rounded border border-border/40 bg-background/30 p-1.5">
            {papers.length === 0 && <div className="py-1 text-center text-[10px] text-muted-foreground/40">列表暂无论文</div>}
            {papers.slice(0, 40).map((p) => {
              const on = paperIds.includes(p.id);
              return (
                <button key={p.id} type="button" onClick={() => togglePaper(p.id)}
                  className={`flex w-full items-center gap-1.5 rounded px-1.5 py-0.5 text-left text-[11px] ${on ? "bg-sky-400/15 text-sky-200" : "text-muted-foreground hover:bg-accent/30"}`}>
                  <input type="checkbox" checked={on} readOnly className="h-3 w-3 accent-sky-500" />
                  <span className="truncate">{p.title}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* 列选择 */}
        <div>
          <div className="mb-1 text-[10px] text-muted-foreground/60">提取列(点击切换):</div>
          <div className="flex flex-wrap gap-1">
            {COMMON_COLS.map((c) => (
              <button key={c.key} type="button" onClick={() => toggleCol(c)}
                className={`rounded-full border px-2 py-0.5 text-[10px] ${cols.some((x) => x.key === c.key) ? "border-sky-400/50 bg-sky-400/15 text-sky-200" : "border-border/60 text-muted-foreground hover:bg-accent/30"}`}>
                {c.label}
              </button>
            ))}
            <input value={customLabel} onChange={(e) => setCustomLabel(e.target.value)} placeholder="自定义列…"
              className="h-5 w-24 rounded border border-border/60 bg-background px-1.5 text-[10px] outline-none focus:border-sky-400/50" />
            <button type="button" onClick={addCustomCol} className="rounded border border-border/60 px-1.5 text-[10px] text-muted-foreground hover:bg-accent/30"><Plus className="h-3 w-3" /></button>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button type="button" onClick={run} disabled={loading}
            className="inline-flex items-center gap-1 rounded-md bg-sky-500 px-3 py-1.5 text-[11px] font-medium text-white hover:bg-sky-400 disabled:opacity-40">
            {loading ? <Loader2 className="h-3 w-3 animate-spin" /> : <Table2 className="h-3 w-3" />}
            {loading ? `提取中(${paperIds.length} 篇)…` : "开始提取"}
          </button>
          {table && (
            <button type="button" onClick={exportCsv}
              className="inline-flex items-center gap-1 rounded-md border border-sky-400/30 px-2 py-1.5 text-[11px] text-sky-300 hover:bg-sky-400/10">
              <Download className="h-3 w-3" /> 导出 CSV
            </button>
          )}
          {msg && <span className="text-[11px] text-muted-foreground">{msg}</span>}
        </div>

        {/* 结果表 */}
        {table && table.length > 0 && (
          <div className="mt-1 overflow-x-auto rounded border border-border/50">
            <table className="w-full min-w-[600px] text-left text-[11px]">
              <thead>
                <tr className="border-b border-border/60 bg-background/40">
                  <th className="px-2 py-1.5 font-medium text-muted-foreground">论文</th>
                  {cols.map((c) => (
                    <th key={c.key} className="px-2 py-1.5 font-medium text-muted-foreground">
                      <button type="button" onClick={() => setSortCol(sortCol === c.key ? null : c.key)} className="hover:text-sky-300">
                        {c.label}{sortCol === c.key ? " ▲" : " ⇅"}
                      </button>
                    </th>
                  ))}
                </tr>
              </thead>
              <tbody>
                {table.map((r, i) => (
                  <tr key={i} className="border-b border-border/30 hover:bg-accent/20">
                    <td className="max-w-[160px] truncate px-2 py-1 align-top font-medium">{r._title}</td>
                    {cols.map((c) => {
                      const v = r[c.key] ?? "";
                      const cell = result?.cells.find((x) => x.paperId === r._paperId && x.columnKey === c.key);
                      return (
                        <td key={c.key} className="px-2 py-1 align-top">
                          <div className="max-w-[240px]">{v || <span className="text-muted-foreground/30">—</span>}</div>
                          {cell?.quote && (
                            <button type="button" onClick={() => setQuotePaper(quotePaper === cell.paperId ? null : cell.paperId)}
                              className="mt-0.5 text-[9px] text-sky-400/70 hover:text-sky-300">引文↗</button>
                          )}
                          {quotePaper === cell?.paperId && cell.quote && (
                            <div className="mt-0.5 rounded bg-black/20 px-1.5 py-1 text-[9px] leading-3 text-muted-foreground">"{cell.quote}"</div>
                          )}
                        </td>
                      );
                    })}
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
